// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.publicalerts.cap;

public  final class Alert extends
    com.google.protobuf.GeneratedMessage
    implements AlertOrBuilder {
  // Use Alert.newBuilder() to construct.
  private Alert(Builder builder) {
    super(builder);
  }
  private Alert(boolean noInit) {}
  
  private static final Alert defaultInstance;
  public static Alert getDefaultInstance() {
    return defaultInstance;
  }
  
  public Alert getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Alert_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Alert_fieldAccessorTable;
  }
  
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    ACTUAL(0, 0),
    EXERCISE(1, 1),
    SYSTEM(2, 2),
    TEST(3, 3),
    DRAFT(4, 4),
    ;
    
    public static final int ACTUAL_VALUE = 0;
    public static final int EXERCISE_VALUE = 1;
    public static final int SYSTEM_VALUE = 2;
    public static final int TEST_VALUE = 3;
    public static final int DRAFT_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static Status valueOf(int value) {
      switch (value) {
        case 0: return ACTUAL;
        case 1: return EXERCISE;
        case 2: return SYSTEM;
        case 3: return TEST;
        case 4: return DRAFT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Alert.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Status[] VALUES = {
      ACTUAL, EXERCISE, SYSTEM, TEST, DRAFT, 
    };
    
    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Status(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:publicalerts.cap.Alert.Status)
  }
  
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    ALERT(0, 0),
    UPDATE(1, 1),
    CANCEL(2, 2),
    ACK(3, 3),
    ERROR(4, 4),
    ;
    
    public static final int ALERT_VALUE = 0;
    public static final int UPDATE_VALUE = 1;
    public static final int CANCEL_VALUE = 2;
    public static final int ACK_VALUE = 3;
    public static final int ERROR_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static MsgType valueOf(int value) {
      switch (value) {
        case 0: return ALERT;
        case 1: return UPDATE;
        case 2: return CANCEL;
        case 3: return ACK;
        case 4: return ERROR;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Alert.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final MsgType[] VALUES = {
      ALERT, UPDATE, CANCEL, ACK, ERROR, 
    };
    
    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:publicalerts.cap.Alert.MsgType)
  }
  
  public enum Scope
      implements com.google.protobuf.ProtocolMessageEnum {
    PUBLIC(0, 0),
    RESTRICTED(1, 1),
    PRIVATE(2, 2),
    ;
    
    public static final int PUBLIC_VALUE = 0;
    public static final int RESTRICTED_VALUE = 1;
    public static final int PRIVATE_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static Scope valueOf(int value) {
      switch (value) {
        case 0: return PUBLIC;
        case 1: return RESTRICTED;
        case 2: return PRIVATE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Scope>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Scope>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Scope>() {
            public Scope findValueByNumber(int number) {
              return Scope.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Alert.getDescriptor().getEnumTypes().get(2);
    }
    
    private static final Scope[] VALUES = {
      PUBLIC, RESTRICTED, PRIVATE, 
    };
    
    public static Scope valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Scope(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:publicalerts.cap.Alert.Scope)
  }
  
  private int bitField0_;
  // required string xmlns = 1;
  public static final int XMLNS_FIELD_NUMBER = 1;
  private java.lang.Object xmlns_;
  public boolean hasXmlns() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  public String getXmlns() {
    java.lang.Object ref = xmlns_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        xmlns_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getXmlnsBytes() {
    java.lang.Object ref = xmlns_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      xmlns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // required string identifier = 2;
  public static final int IDENTIFIER_FIELD_NUMBER = 2;
  private java.lang.Object identifier_;
  public boolean hasIdentifier() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  public String getIdentifier() {
    java.lang.Object ref = identifier_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        identifier_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getIdentifierBytes() {
    java.lang.Object ref = identifier_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      identifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // required string sender = 3;
  public static final int SENDER_FIELD_NUMBER = 3;
  private java.lang.Object sender_;
  public boolean hasSender() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  public String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        sender_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // optional string password = 4 [deprecated = true];
  public static final int PASSWORD_FIELD_NUMBER = 4;
  private java.lang.Object password_;
  @java.lang.Deprecated public boolean hasPassword() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  @java.lang.Deprecated public String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        password_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // required string sent = 5;
  public static final int SENT_FIELD_NUMBER = 5;
  private java.lang.Object sent_;
  public boolean hasSent() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  public String getSent() {
    java.lang.Object ref = sent_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        sent_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getSentBytes() {
    java.lang.Object ref = sent_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      sent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // required .publicalerts.cap.Alert.Status status = 6;
  public static final int STATUS_FIELD_NUMBER = 6;
  private com.google.publicalerts.cap.Alert.Status status_;
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  public com.google.publicalerts.cap.Alert.Status getStatus() {
    return status_;
  }
  
  // required .publicalerts.cap.Alert.MsgType msg_type = 7;
  public static final int MSG_TYPE_FIELD_NUMBER = 7;
  private com.google.publicalerts.cap.Alert.MsgType msgType_;
  public boolean hasMsgType() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  public com.google.publicalerts.cap.Alert.MsgType getMsgType() {
    return msgType_;
  }
  
  // optional string source = 8;
  public static final int SOURCE_FIELD_NUMBER = 8;
  private java.lang.Object source_;
  public boolean hasSource() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  public String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        source_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // optional .publicalerts.cap.Alert.Scope scope = 9;
  public static final int SCOPE_FIELD_NUMBER = 9;
  private com.google.publicalerts.cap.Alert.Scope scope_;
  public boolean hasScope() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  public com.google.publicalerts.cap.Alert.Scope getScope() {
    return scope_;
  }
  
  // optional string restriction = 10;
  public static final int RESTRICTION_FIELD_NUMBER = 10;
  private java.lang.Object restriction_;
  public boolean hasRestriction() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  public String getRestriction() {
    java.lang.Object ref = restriction_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        restriction_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getRestrictionBytes() {
    java.lang.Object ref = restriction_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      restriction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // optional .publicalerts.cap.Group addresses = 11;
  public static final int ADDRESSES_FIELD_NUMBER = 11;
  private com.google.publicalerts.cap.Group addresses_;
  public boolean hasAddresses() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  public com.google.publicalerts.cap.Group getAddresses() {
    return addresses_;
  }
  public com.google.publicalerts.cap.GroupOrBuilder getAddressesOrBuilder() {
    return addresses_;
  }
  
  // repeated string code = 12;
  public static final int CODE_FIELD_NUMBER = 12;
  private com.google.protobuf.LazyStringList code_;
  public java.util.List<String>
      getCodeList() {
    return code_;
  }
  public int getCodeCount() {
    return code_.size();
  }
  public String getCode(int index) {
    return code_.get(index);
  }
  
  // optional string note = 13;
  public static final int NOTE_FIELD_NUMBER = 13;
  private java.lang.Object note_;
  public boolean hasNote() {
    return ((bitField0_ & 0x00000800) == 0x00000800);
  }
  public String getNote() {
    java.lang.Object ref = note_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        note_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getNoteBytes() {
    java.lang.Object ref = note_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      note_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  // optional .publicalerts.cap.Group references = 14;
  public static final int REFERENCES_FIELD_NUMBER = 14;
  private com.google.publicalerts.cap.Group references_;
  public boolean hasReferences() {
    return ((bitField0_ & 0x00001000) == 0x00001000);
  }
  public com.google.publicalerts.cap.Group getReferences() {
    return references_;
  }
  public com.google.publicalerts.cap.GroupOrBuilder getReferencesOrBuilder() {
    return references_;
  }
  
  // optional .publicalerts.cap.Group incidents = 15;
  public static final int INCIDENTS_FIELD_NUMBER = 15;
  private com.google.publicalerts.cap.Group incidents_;
  public boolean hasIncidents() {
    return ((bitField0_ & 0x00002000) == 0x00002000);
  }
  public com.google.publicalerts.cap.Group getIncidents() {
    return incidents_;
  }
  public com.google.publicalerts.cap.GroupOrBuilder getIncidentsOrBuilder() {
    return incidents_;
  }
  
  // repeated .publicalerts.cap.Info info = 16;
  public static final int INFO_FIELD_NUMBER = 16;
  private java.util.List<com.google.publicalerts.cap.Info> info_;
  public java.util.List<com.google.publicalerts.cap.Info> getInfoList() {
    return info_;
  }
  public java.util.List<? extends com.google.publicalerts.cap.InfoOrBuilder> 
      getInfoOrBuilderList() {
    return info_;
  }
  public int getInfoCount() {
    return info_.size();
  }
  public com.google.publicalerts.cap.Info getInfo(int index) {
    return info_.get(index);
  }
  public com.google.publicalerts.cap.InfoOrBuilder getInfoOrBuilder(
      int index) {
    return info_.get(index);
  }
  
  private void initFields() {
    xmlns_ = "";
    identifier_ = "";
    sender_ = "";
    password_ = "";
    sent_ = "";
    status_ = com.google.publicalerts.cap.Alert.Status.ACTUAL;
    msgType_ = com.google.publicalerts.cap.Alert.MsgType.ALERT;
    source_ = "";
    scope_ = com.google.publicalerts.cap.Alert.Scope.PUBLIC;
    restriction_ = "";
    addresses_ = com.google.publicalerts.cap.Group.getDefaultInstance();
    code_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    note_ = "";
    references_ = com.google.publicalerts.cap.Group.getDefaultInstance();
    incidents_ = com.google.publicalerts.cap.Group.getDefaultInstance();
    info_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;
    
    if (!hasXmlns()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasIdentifier()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSender()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSent()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMsgType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getInfoCount(); i++) {
      if (!getInfo(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getXmlnsBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getIdentifierBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getSenderBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getPasswordBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getSentBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeEnum(6, status_.getNumber());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeEnum(7, msgType_.getNumber());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBytes(8, getSourceBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeEnum(9, scope_.getNumber());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(10, getRestrictionBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeMessage(11, addresses_);
    }
    for (int i = 0; i < code_.size(); i++) {
      output.writeBytes(12, code_.getByteString(i));
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      output.writeBytes(13, getNoteBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      output.writeMessage(14, references_);
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      output.writeMessage(15, incidents_);
    }
    for (int i = 0; i < info_.size(); i++) {
      output.writeMessage(16, info_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getXmlnsBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getIdentifierBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getSenderBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getPasswordBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getSentBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_.getNumber());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, msgType_.getNumber());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getSourceBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, scope_.getNumber());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getRestrictionBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, addresses_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < code_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(code_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getCodeList().size();
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, getNoteBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, references_);
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, incidents_);
    }
    for (int i = 0; i < info_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, info_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }
  
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.publicalerts.cap.Alert)) {
      return super.equals(obj);
    }
    com.google.publicalerts.cap.Alert other = (com.google.publicalerts.cap.Alert) obj;
    
    boolean result = true;
    result = result && (hasXmlns() == other.hasXmlns());
    if (hasXmlns()) {
      result = result && getXmlns()
          .equals(other.getXmlns());
    }
    result = result && (hasIdentifier() == other.hasIdentifier());
    if (hasIdentifier()) {
      result = result && getIdentifier()
          .equals(other.getIdentifier());
    }
    result = result && (hasSender() == other.hasSender());
    if (hasSender()) {
      result = result && getSender()
          .equals(other.getSender());
    }
    result = result && (hasPassword() == other.hasPassword());
    if (hasPassword()) {
      result = result && getPassword()
          .equals(other.getPassword());
    }
    result = result && (hasSent() == other.hasSent());
    if (hasSent()) {
      result = result && getSent()
          .equals(other.getSent());
    }
    result = result && (hasStatus() == other.hasStatus());
    if (hasStatus()) {
      result = result &&
          (getStatus() == other.getStatus());
    }
    result = result && (hasMsgType() == other.hasMsgType());
    if (hasMsgType()) {
      result = result &&
          (getMsgType() == other.getMsgType());
    }
    result = result && (hasSource() == other.hasSource());
    if (hasSource()) {
      result = result && getSource()
          .equals(other.getSource());
    }
    result = result && (hasScope() == other.hasScope());
    if (hasScope()) {
      result = result &&
          (getScope() == other.getScope());
    }
    result = result && (hasRestriction() == other.hasRestriction());
    if (hasRestriction()) {
      result = result && getRestriction()
          .equals(other.getRestriction());
    }
    result = result && (hasAddresses() == other.hasAddresses());
    if (hasAddresses()) {
      result = result && getAddresses()
          .equals(other.getAddresses());
    }
    result = result && getCodeList()
        .equals(other.getCodeList());
    result = result && (hasNote() == other.hasNote());
    if (hasNote()) {
      result = result && getNote()
          .equals(other.getNote());
    }
    result = result && (hasReferences() == other.hasReferences());
    if (hasReferences()) {
      result = result && getReferences()
          .equals(other.getReferences());
    }
    result = result && (hasIncidents() == other.hasIncidents());
    if (hasIncidents()) {
      result = result && getIncidents()
          .equals(other.getIncidents());
    }
    result = result && getInfoList()
        .equals(other.getInfoList());
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }
  
  @java.lang.Override
  public int hashCode() {
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasXmlns()) {
      hash = (37 * hash) + XMLNS_FIELD_NUMBER;
      hash = (53 * hash) + getXmlns().hashCode();
    }
    if (hasIdentifier()) {
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
    }
    if (hasSender()) {
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
    }
    if (hasPassword()) {
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
    }
    if (hasSent()) {
      hash = (37 * hash) + SENT_FIELD_NUMBER;
      hash = (53 * hash) + getSent().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + hashEnum(getStatus());
    }
    if (hasMsgType()) {
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + hashEnum(getMsgType());
    }
    if (hasSource()) {
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
    }
    if (hasScope()) {
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + hashEnum(getScope());
    }
    if (hasRestriction()) {
      hash = (37 * hash) + RESTRICTION_FIELD_NUMBER;
      hash = (53 * hash) + getRestriction().hashCode();
    }
    if (hasAddresses()) {
      hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
      hash = (53 * hash) + getAddresses().hashCode();
    }
    if (getCodeCount() > 0) {
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCodeList().hashCode();
    }
    if (hasNote()) {
      hash = (37 * hash) + NOTE_FIELD_NUMBER;
      hash = (53 * hash) + getNote().hashCode();
    }
    if (hasReferences()) {
      hash = (37 * hash) + REFERENCES_FIELD_NUMBER;
      hash = (53 * hash) + getReferences().hashCode();
    }
    if (hasIncidents()) {
      hash = (37 * hash) + INCIDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getIncidents().hashCode();
    }
    if (getInfoCount() > 0) {
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    return hash;
  }
  
  public static com.google.publicalerts.cap.Alert parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static com.google.publicalerts.cap.Alert parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static com.google.publicalerts.cap.Alert parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static com.google.publicalerts.cap.Alert parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static com.google.publicalerts.cap.Alert parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static com.google.publicalerts.cap.Alert parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static com.google.publicalerts.cap.Alert parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static com.google.publicalerts.cap.Alert parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static com.google.publicalerts.cap.Alert parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static com.google.publicalerts.cap.Alert parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.publicalerts.cap.Alert prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.publicalerts.cap.AlertOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Alert_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Alert_fieldAccessorTable;
    }
    
    // Construct using com.google.publicalerts.cap.Alert.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }
    
    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getAddressesFieldBuilder();
        getReferencesFieldBuilder();
        getIncidentsFieldBuilder();
        getInfoFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }
    
    public Builder clear() {
      super.clear();
      xmlns_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      identifier_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      sender_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      password_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      sent_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = com.google.publicalerts.cap.Alert.Status.ACTUAL;
      bitField0_ = (bitField0_ & ~0x00000020);
      msgType_ = com.google.publicalerts.cap.Alert.MsgType.ALERT;
      bitField0_ = (bitField0_ & ~0x00000040);
      source_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      scope_ = com.google.publicalerts.cap.Alert.Scope.PUBLIC;
      bitField0_ = (bitField0_ & ~0x00000100);
      restriction_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      if (addressesBuilder_ == null) {
        addresses_ = com.google.publicalerts.cap.Group.getDefaultInstance();
      } else {
        addressesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      code_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000800);
      note_ = "";
      bitField0_ = (bitField0_ & ~0x00001000);
      if (referencesBuilder_ == null) {
        references_ = com.google.publicalerts.cap.Group.getDefaultInstance();
      } else {
        referencesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00002000);
      if (incidentsBuilder_ == null) {
        incidents_ = com.google.publicalerts.cap.Group.getDefaultInstance();
      } else {
        incidentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00004000);
      if (infoBuilder_ == null) {
        info_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00008000);
      } else {
        infoBuilder_.clear();
      }
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.publicalerts.cap.Alert.getDescriptor();
    }
    
    public com.google.publicalerts.cap.Alert getDefaultInstanceForType() {
      return com.google.publicalerts.cap.Alert.getDefaultInstance();
    }
    
    public com.google.publicalerts.cap.Alert build() {
      com.google.publicalerts.cap.Alert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }
    
    private com.google.publicalerts.cap.Alert buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      com.google.publicalerts.cap.Alert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return result;
    }
    
    public com.google.publicalerts.cap.Alert buildPartial() {
      com.google.publicalerts.cap.Alert result = new com.google.publicalerts.cap.Alert(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.xmlns_ = xmlns_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.identifier_ = identifier_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.sender_ = sender_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.password_ = password_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.sent_ = sent_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.msgType_ = msgType_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.source_ = source_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.scope_ = scope_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.restriction_ = restriction_;
      if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
        to_bitField0_ |= 0x00000400;
      }
      if (addressesBuilder_ == null) {
        result.addresses_ = addresses_;
      } else {
        result.addresses_ = addressesBuilder_.build();
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        code_ = new com.google.protobuf.UnmodifiableLazyStringList(
            code_);
        bitField0_ = (bitField0_ & ~0x00000800);
      }
      result.code_ = code_;
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00000800;
      }
      result.note_ = note_;
      if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
        to_bitField0_ |= 0x00001000;
      }
      if (referencesBuilder_ == null) {
        result.references_ = references_;
      } else {
        result.references_ = referencesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
        to_bitField0_ |= 0x00002000;
      }
      if (incidentsBuilder_ == null) {
        result.incidents_ = incidents_;
      } else {
        result.incidents_ = incidentsBuilder_.build();
      }
      if (infoBuilder_ == null) {
        if (((bitField0_ & 0x00008000) == 0x00008000)) {
          info_ = java.util.Collections.unmodifiableList(info_);
          bitField0_ = (bitField0_ & ~0x00008000);
        }
        result.info_ = info_;
      } else {
        result.info_ = infoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.publicalerts.cap.Alert) {
        return mergeFrom((com.google.publicalerts.cap.Alert)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(com.google.publicalerts.cap.Alert other) {
      if (other == com.google.publicalerts.cap.Alert.getDefaultInstance()) return this;
      if (other.hasXmlns()) {
        setXmlns(other.getXmlns());
      }
      if (other.hasIdentifier()) {
        setIdentifier(other.getIdentifier());
      }
      if (other.hasSender()) {
        setSender(other.getSender());
      }
      if (other.hasPassword()) {
        setPassword(other.getPassword());
      }
      if (other.hasSent()) {
        setSent(other.getSent());
      }
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (other.hasMsgType()) {
        setMsgType(other.getMsgType());
      }
      if (other.hasSource()) {
        setSource(other.getSource());
      }
      if (other.hasScope()) {
        setScope(other.getScope());
      }
      if (other.hasRestriction()) {
        setRestriction(other.getRestriction());
      }
      if (other.hasAddresses()) {
        mergeAddresses(other.getAddresses());
      }
      if (!other.code_.isEmpty()) {
        if (code_.isEmpty()) {
          code_ = other.code_;
          bitField0_ = (bitField0_ & ~0x00000800);
        } else {
          ensureCodeIsMutable();
          code_.addAll(other.code_);
        }
        onChanged();
      }
      if (other.hasNote()) {
        setNote(other.getNote());
      }
      if (other.hasReferences()) {
        mergeReferences(other.getReferences());
      }
      if (other.hasIncidents()) {
        mergeIncidents(other.getIncidents());
      }
      if (infoBuilder_ == null) {
        if (!other.info_.isEmpty()) {
          if (info_.isEmpty()) {
            info_ = other.info_;
            bitField0_ = (bitField0_ & ~0x00008000);
          } else {
            ensureInfoIsMutable();
            info_.addAll(other.info_);
          }
          onChanged();
        }
      } else {
        if (!other.info_.isEmpty()) {
          if (infoBuilder_.isEmpty()) {
            infoBuilder_.dispose();
            infoBuilder_ = null;
            info_ = other.info_;
            bitField0_ = (bitField0_ & ~0x00008000);
            infoBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getInfoFieldBuilder() : null;
          } else {
            infoBuilder_.addAllMessages(other.info_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public final boolean isInitialized() {
      if (!hasXmlns()) {
        
        return false;
      }
      if (!hasIdentifier()) {
        
        return false;
      }
      if (!hasSender()) {
        
        return false;
      }
      if (!hasSent()) {
        
        return false;
      }
      if (!hasStatus()) {
        
        return false;
      }
      if (!hasMsgType()) {
        
        return false;
      }
      for (int i = 0; i < getInfoCount(); i++) {
        if (!getInfo(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            onChanged();
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            xmlns_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            identifier_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            sender_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            password_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            sent_ = input.readBytes();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
            com.google.publicalerts.cap.Alert.Status value = com.google.publicalerts.cap.Alert.Status.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              status_ = value;
            }
            break;
          }
          case 56: {
            int rawValue = input.readEnum();
            com.google.publicalerts.cap.Alert.MsgType value = com.google.publicalerts.cap.Alert.MsgType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(7, rawValue);
            } else {
              bitField0_ |= 0x00000040;
              msgType_ = value;
            }
            break;
          }
          case 66: {
            bitField0_ |= 0x00000080;
            source_ = input.readBytes();
            break;
          }
          case 72: {
            int rawValue = input.readEnum();
            com.google.publicalerts.cap.Alert.Scope value = com.google.publicalerts.cap.Alert.Scope.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(9, rawValue);
            } else {
              bitField0_ |= 0x00000100;
              scope_ = value;
            }
            break;
          }
          case 82: {
            bitField0_ |= 0x00000200;
            restriction_ = input.readBytes();
            break;
          }
          case 90: {
            com.google.publicalerts.cap.Group.Builder subBuilder = com.google.publicalerts.cap.Group.newBuilder();
            if (hasAddresses()) {
              subBuilder.mergeFrom(getAddresses());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setAddresses(subBuilder.buildPartial());
            break;
          }
          case 98: {
            ensureCodeIsMutable();
            code_.add(input.readBytes());
            break;
          }
          case 106: {
            bitField0_ |= 0x00001000;
            note_ = input.readBytes();
            break;
          }
          case 114: {
            com.google.publicalerts.cap.Group.Builder subBuilder = com.google.publicalerts.cap.Group.newBuilder();
            if (hasReferences()) {
              subBuilder.mergeFrom(getReferences());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setReferences(subBuilder.buildPartial());
            break;
          }
          case 122: {
            com.google.publicalerts.cap.Group.Builder subBuilder = com.google.publicalerts.cap.Group.newBuilder();
            if (hasIncidents()) {
              subBuilder.mergeFrom(getIncidents());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setIncidents(subBuilder.buildPartial());
            break;
          }
          case 130: {
            com.google.publicalerts.cap.Info.Builder subBuilder = com.google.publicalerts.cap.Info.newBuilder();
            input.readMessage(subBuilder, extensionRegistry);
            addInfo(subBuilder.buildPartial());
            break;
          }
        }
      }
    }
    
    private int bitField0_;
    
    // required string xmlns = 1;
    private java.lang.Object xmlns_ = "";
    public boolean hasXmlns() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getXmlns() {
      java.lang.Object ref = xmlns_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        xmlns_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setXmlns(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      xmlns_ = value;
      onChanged();
      return this;
    }
    public Builder clearXmlns() {
      bitField0_ = (bitField0_ & ~0x00000001);
      xmlns_ = getDefaultInstance().getXmlns();
      onChanged();
      return this;
    }
    void setXmlns(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000001;
      xmlns_ = value;
      onChanged();
    }
    
    // required string identifier = 2;
    private java.lang.Object identifier_ = "";
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        identifier_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setIdentifier(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      identifier_ = value;
      onChanged();
      return this;
    }
    public Builder clearIdentifier() {
      bitField0_ = (bitField0_ & ~0x00000002);
      identifier_ = getDefaultInstance().getIdentifier();
      onChanged();
      return this;
    }
    void setIdentifier(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000002;
      identifier_ = value;
      onChanged();
    }
    
    // required string sender = 3;
    private java.lang.Object sender_ = "";
    public boolean hasSender() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setSender(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      sender_ = value;
      onChanged();
      return this;
    }
    public Builder clearSender() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    void setSender(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000004;
      sender_ = value;
      onChanged();
    }
    
    // optional string password = 4 [deprecated = true];
    private java.lang.Object password_ = "";
    @java.lang.Deprecated public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    @java.lang.Deprecated public String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    @java.lang.Deprecated public Builder setPassword(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      password_ = value;
      onChanged();
      return this;
    }
    @java.lang.Deprecated public Builder clearPassword() {
      bitField0_ = (bitField0_ & ~0x00000008);
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    void setPassword(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000008;
      password_ = value;
      onChanged();
    }
    
    // required string sent = 5;
    private java.lang.Object sent_ = "";
    public boolean hasSent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSent() {
      java.lang.Object ref = sent_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        sent_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setSent(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      sent_ = value;
      onChanged();
      return this;
    }
    public Builder clearSent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sent_ = getDefaultInstance().getSent();
      onChanged();
      return this;
    }
    void setSent(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000010;
      sent_ = value;
      onChanged();
    }
    
    // required .publicalerts.cap.Alert.Status status = 6;
    private com.google.publicalerts.cap.Alert.Status status_ = com.google.publicalerts.cap.Alert.Status.ACTUAL;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.publicalerts.cap.Alert.Status getStatus() {
      return status_;
    }
    public Builder setStatus(com.google.publicalerts.cap.Alert.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      status_ = value;
      onChanged();
      return this;
    }
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000020);
      status_ = com.google.publicalerts.cap.Alert.Status.ACTUAL;
      onChanged();
      return this;
    }
    
    // required .publicalerts.cap.Alert.MsgType msg_type = 7;
    private com.google.publicalerts.cap.Alert.MsgType msgType_ = com.google.publicalerts.cap.Alert.MsgType.ALERT;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.google.publicalerts.cap.Alert.MsgType getMsgType() {
      return msgType_;
    }
    public Builder setMsgType(com.google.publicalerts.cap.Alert.MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      msgType_ = value;
      onChanged();
      return this;
    }
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      msgType_ = com.google.publicalerts.cap.Alert.MsgType.ALERT;
      onChanged();
      return this;
    }
    
    // optional string source = 8;
    private java.lang.Object source_ = "";
    public boolean hasSource() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setSource(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      source_ = value;
      onChanged();
      return this;
    }
    public Builder clearSource() {
      bitField0_ = (bitField0_ & ~0x00000080);
      source_ = getDefaultInstance().getSource();
      onChanged();
      return this;
    }
    void setSource(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000080;
      source_ = value;
      onChanged();
    }
    
    // optional .publicalerts.cap.Alert.Scope scope = 9;
    private com.google.publicalerts.cap.Alert.Scope scope_ = com.google.publicalerts.cap.Alert.Scope.PUBLIC;
    public boolean hasScope() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.google.publicalerts.cap.Alert.Scope getScope() {
      return scope_;
    }
    public Builder setScope(com.google.publicalerts.cap.Alert.Scope value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000100;
      scope_ = value;
      onChanged();
      return this;
    }
    public Builder clearScope() {
      bitField0_ = (bitField0_ & ~0x00000100);
      scope_ = com.google.publicalerts.cap.Alert.Scope.PUBLIC;
      onChanged();
      return this;
    }
    
    // optional string restriction = 10;
    private java.lang.Object restriction_ = "";
    public boolean hasRestriction() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getRestriction() {
      java.lang.Object ref = restriction_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        restriction_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setRestriction(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      restriction_ = value;
      onChanged();
      return this;
    }
    public Builder clearRestriction() {
      bitField0_ = (bitField0_ & ~0x00000200);
      restriction_ = getDefaultInstance().getRestriction();
      onChanged();
      return this;
    }
    void setRestriction(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000200;
      restriction_ = value;
      onChanged();
    }
    
    // optional .publicalerts.cap.Group addresses = 11;
    private com.google.publicalerts.cap.Group addresses_ = com.google.publicalerts.cap.Group.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder> addressesBuilder_;
    public boolean hasAddresses() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public com.google.publicalerts.cap.Group getAddresses() {
      if (addressesBuilder_ == null) {
        return addresses_;
      } else {
        return addressesBuilder_.getMessage();
      }
    }
    public Builder setAddresses(com.google.publicalerts.cap.Group value) {
      if (addressesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        addresses_ = value;
        onChanged();
      } else {
        addressesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    public Builder setAddresses(
        com.google.publicalerts.cap.Group.Builder builderForValue) {
      if (addressesBuilder_ == null) {
        addresses_ = builderForValue.build();
        onChanged();
      } else {
        addressesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    public Builder mergeAddresses(com.google.publicalerts.cap.Group value) {
      if (addressesBuilder_ == null) {
        if (((bitField0_ & 0x00000400) == 0x00000400) &&
            addresses_ != com.google.publicalerts.cap.Group.getDefaultInstance()) {
          addresses_ =
            com.google.publicalerts.cap.Group.newBuilder(addresses_).mergeFrom(value).buildPartial();
        } else {
          addresses_ = value;
        }
        onChanged();
      } else {
        addressesBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    public Builder clearAddresses() {
      if (addressesBuilder_ == null) {
        addresses_ = com.google.publicalerts.cap.Group.getDefaultInstance();
        onChanged();
      } else {
        addressesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      return this;
    }
    public com.google.publicalerts.cap.Group.Builder getAddressesBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getAddressesFieldBuilder().getBuilder();
    }
    public com.google.publicalerts.cap.GroupOrBuilder getAddressesOrBuilder() {
      if (addressesBuilder_ != null) {
        return addressesBuilder_.getMessageOrBuilder();
      } else {
        return addresses_;
      }
    }
    private com.google.protobuf.SingleFieldBuilder<
        com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder> 
        getAddressesFieldBuilder() {
      if (addressesBuilder_ == null) {
        addressesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder>(
                addresses_,
                getParentForChildren(),
                isClean());
        addresses_ = null;
      }
      return addressesBuilder_;
    }
    
    // repeated string code = 12;
    private com.google.protobuf.LazyStringList code_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCodeIsMutable() {
      if (!((bitField0_ & 0x00000800) == 0x00000800)) {
        code_ = new com.google.protobuf.LazyStringArrayList(code_);
        bitField0_ |= 0x00000800;
       }
    }
    public java.util.List<String>
        getCodeList() {
      return java.util.Collections.unmodifiableList(code_);
    }
    public int getCodeCount() {
      return code_.size();
    }
    public String getCode(int index) {
      return code_.get(index);
    }
    public Builder setCode(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCodeIsMutable();
      code_.set(index, value);
      onChanged();
      return this;
    }
    public Builder addCode(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCodeIsMutable();
      code_.add(value);
      onChanged();
      return this;
    }
    public Builder addAllCode(
        java.lang.Iterable<String> values) {
      ensureCodeIsMutable();
      super.addAll(values, code_);
      onChanged();
      return this;
    }
    public Builder clearCode() {
      code_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    void addCode(com.google.protobuf.ByteString value) {
      ensureCodeIsMutable();
      code_.add(value);
      onChanged();
    }
    
    // optional string note = 13;
    private java.lang.Object note_ = "";
    public boolean hasNote() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getNote() {
      java.lang.Object ref = note_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        note_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setNote(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      note_ = value;
      onChanged();
      return this;
    }
    public Builder clearNote() {
      bitField0_ = (bitField0_ & ~0x00001000);
      note_ = getDefaultInstance().getNote();
      onChanged();
      return this;
    }
    void setNote(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00001000;
      note_ = value;
      onChanged();
    }
    
    // optional .publicalerts.cap.Group references = 14;
    private com.google.publicalerts.cap.Group references_ = com.google.publicalerts.cap.Group.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder> referencesBuilder_;
    public boolean hasReferences() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public com.google.publicalerts.cap.Group getReferences() {
      if (referencesBuilder_ == null) {
        return references_;
      } else {
        return referencesBuilder_.getMessage();
      }
    }
    public Builder setReferences(com.google.publicalerts.cap.Group value) {
      if (referencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        references_ = value;
        onChanged();
      } else {
        referencesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00002000;
      return this;
    }
    public Builder setReferences(
        com.google.publicalerts.cap.Group.Builder builderForValue) {
      if (referencesBuilder_ == null) {
        references_ = builderForValue.build();
        onChanged();
      } else {
        referencesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00002000;
      return this;
    }
    public Builder mergeReferences(com.google.publicalerts.cap.Group value) {
      if (referencesBuilder_ == null) {
        if (((bitField0_ & 0x00002000) == 0x00002000) &&
            references_ != com.google.publicalerts.cap.Group.getDefaultInstance()) {
          references_ =
            com.google.publicalerts.cap.Group.newBuilder(references_).mergeFrom(value).buildPartial();
        } else {
          references_ = value;
        }
        onChanged();
      } else {
        referencesBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00002000;
      return this;
    }
    public Builder clearReferences() {
      if (referencesBuilder_ == null) {
        references_ = com.google.publicalerts.cap.Group.getDefaultInstance();
        onChanged();
      } else {
        referencesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00002000);
      return this;
    }
    public com.google.publicalerts.cap.Group.Builder getReferencesBuilder() {
      bitField0_ |= 0x00002000;
      onChanged();
      return getReferencesFieldBuilder().getBuilder();
    }
    public com.google.publicalerts.cap.GroupOrBuilder getReferencesOrBuilder() {
      if (referencesBuilder_ != null) {
        return referencesBuilder_.getMessageOrBuilder();
      } else {
        return references_;
      }
    }
    private com.google.protobuf.SingleFieldBuilder<
        com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder> 
        getReferencesFieldBuilder() {
      if (referencesBuilder_ == null) {
        referencesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder>(
                references_,
                getParentForChildren(),
                isClean());
        references_ = null;
      }
      return referencesBuilder_;
    }
    
    // optional .publicalerts.cap.Group incidents = 15;
    private com.google.publicalerts.cap.Group incidents_ = com.google.publicalerts.cap.Group.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder> incidentsBuilder_;
    public boolean hasIncidents() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public com.google.publicalerts.cap.Group getIncidents() {
      if (incidentsBuilder_ == null) {
        return incidents_;
      } else {
        return incidentsBuilder_.getMessage();
      }
    }
    public Builder setIncidents(com.google.publicalerts.cap.Group value) {
      if (incidentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        incidents_ = value;
        onChanged();
      } else {
        incidentsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00004000;
      return this;
    }
    public Builder setIncidents(
        com.google.publicalerts.cap.Group.Builder builderForValue) {
      if (incidentsBuilder_ == null) {
        incidents_ = builderForValue.build();
        onChanged();
      } else {
        incidentsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00004000;
      return this;
    }
    public Builder mergeIncidents(com.google.publicalerts.cap.Group value) {
      if (incidentsBuilder_ == null) {
        if (((bitField0_ & 0x00004000) == 0x00004000) &&
            incidents_ != com.google.publicalerts.cap.Group.getDefaultInstance()) {
          incidents_ =
            com.google.publicalerts.cap.Group.newBuilder(incidents_).mergeFrom(value).buildPartial();
        } else {
          incidents_ = value;
        }
        onChanged();
      } else {
        incidentsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00004000;
      return this;
    }
    public Builder clearIncidents() {
      if (incidentsBuilder_ == null) {
        incidents_ = com.google.publicalerts.cap.Group.getDefaultInstance();
        onChanged();
      } else {
        incidentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00004000);
      return this;
    }
    public com.google.publicalerts.cap.Group.Builder getIncidentsBuilder() {
      bitField0_ |= 0x00004000;
      onChanged();
      return getIncidentsFieldBuilder().getBuilder();
    }
    public com.google.publicalerts.cap.GroupOrBuilder getIncidentsOrBuilder() {
      if (incidentsBuilder_ != null) {
        return incidentsBuilder_.getMessageOrBuilder();
      } else {
        return incidents_;
      }
    }
    private com.google.protobuf.SingleFieldBuilder<
        com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder> 
        getIncidentsFieldBuilder() {
      if (incidentsBuilder_ == null) {
        incidentsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.publicalerts.cap.Group, com.google.publicalerts.cap.Group.Builder, com.google.publicalerts.cap.GroupOrBuilder>(
                incidents_,
                getParentForChildren(),
                isClean());
        incidents_ = null;
      }
      return incidentsBuilder_;
    }
    
    // repeated .publicalerts.cap.Info info = 16;
    private java.util.List<com.google.publicalerts.cap.Info> info_ =
      java.util.Collections.emptyList();
    private void ensureInfoIsMutable() {
      if (!((bitField0_ & 0x00008000) == 0x00008000)) {
        info_ = new java.util.ArrayList<com.google.publicalerts.cap.Info>(info_);
        bitField0_ |= 0x00008000;
       }
    }
    
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Info, com.google.publicalerts.cap.Info.Builder, com.google.publicalerts.cap.InfoOrBuilder> infoBuilder_;
    
    public java.util.List<com.google.publicalerts.cap.Info> getInfoList() {
      if (infoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(info_);
      } else {
        return infoBuilder_.getMessageList();
      }
    }
    public int getInfoCount() {
      if (infoBuilder_ == null) {
        return info_.size();
      } else {
        return infoBuilder_.getCount();
      }
    }
    public com.google.publicalerts.cap.Info getInfo(int index) {
      if (infoBuilder_ == null) {
        return info_.get(index);
      } else {
        return infoBuilder_.getMessage(index);
      }
    }
    public Builder setInfo(
        int index, com.google.publicalerts.cap.Info value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfoIsMutable();
        info_.set(index, value);
        onChanged();
      } else {
        infoBuilder_.setMessage(index, value);
      }
      return this;
    }
    public Builder setInfo(
        int index, com.google.publicalerts.cap.Info.Builder builderForValue) {
      if (infoBuilder_ == null) {
        ensureInfoIsMutable();
        info_.set(index, builderForValue.build());
        onChanged();
      } else {
        infoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    public Builder addInfo(com.google.publicalerts.cap.Info value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfoIsMutable();
        info_.add(value);
        onChanged();
      } else {
        infoBuilder_.addMessage(value);
      }
      return this;
    }
    public Builder addInfo(
        int index, com.google.publicalerts.cap.Info value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfoIsMutable();
        info_.add(index, value);
        onChanged();
      } else {
        infoBuilder_.addMessage(index, value);
      }
      return this;
    }
    public Builder addInfo(
        com.google.publicalerts.cap.Info.Builder builderForValue) {
      if (infoBuilder_ == null) {
        ensureInfoIsMutable();
        info_.add(builderForValue.build());
        onChanged();
      } else {
        infoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    public Builder addInfo(
        int index, com.google.publicalerts.cap.Info.Builder builderForValue) {
      if (infoBuilder_ == null) {
        ensureInfoIsMutable();
        info_.add(index, builderForValue.build());
        onChanged();
      } else {
        infoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    public Builder addAllInfo(
        java.lang.Iterable<? extends com.google.publicalerts.cap.Info> values) {
      if (infoBuilder_ == null) {
        ensureInfoIsMutable();
        super.addAll(values, info_);
        onChanged();
      } else {
        infoBuilder_.addAllMessages(values);
      }
      return this;
    }
    public Builder clearInfo() {
      if (infoBuilder_ == null) {
        info_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00008000);
        onChanged();
      } else {
        infoBuilder_.clear();
      }
      return this;
    }
    public Builder removeInfo(int index) {
      if (infoBuilder_ == null) {
        ensureInfoIsMutable();
        info_.remove(index);
        onChanged();
      } else {
        infoBuilder_.remove(index);
      }
      return this;
    }
    public com.google.publicalerts.cap.Info.Builder getInfoBuilder(
        int index) {
      return getInfoFieldBuilder().getBuilder(index);
    }
    public com.google.publicalerts.cap.InfoOrBuilder getInfoOrBuilder(
        int index) {
      if (infoBuilder_ == null) {
        return info_.get(index);  } else {
        return infoBuilder_.getMessageOrBuilder(index);
      }
    }
    public java.util.List<? extends com.google.publicalerts.cap.InfoOrBuilder> 
         getInfoOrBuilderList() {
      if (infoBuilder_ != null) {
        return infoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(info_);
      }
    }
    public com.google.publicalerts.cap.Info.Builder addInfoBuilder() {
      return getInfoFieldBuilder().addBuilder(
          com.google.publicalerts.cap.Info.getDefaultInstance());
    }
    public com.google.publicalerts.cap.Info.Builder addInfoBuilder(
        int index) {
      return getInfoFieldBuilder().addBuilder(
          index, com.google.publicalerts.cap.Info.getDefaultInstance());
    }
    public java.util.List<com.google.publicalerts.cap.Info.Builder> 
         getInfoBuilderList() {
      return getInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Info, com.google.publicalerts.cap.Info.Builder, com.google.publicalerts.cap.InfoOrBuilder> 
        getInfoFieldBuilder() {
      if (infoBuilder_ == null) {
        infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.publicalerts.cap.Info, com.google.publicalerts.cap.Info.Builder, com.google.publicalerts.cap.InfoOrBuilder>(
                info_,
                ((bitField0_ & 0x00008000) == 0x00008000),
                getParentForChildren(),
                isClean());
        info_ = null;
      }
      return infoBuilder_;
    }
    
    // @@protoc_insertion_point(builder_scope:publicalerts.cap.Alert)
  }
  
  static {
    defaultInstance = new Alert(true);
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:publicalerts.cap.Alert)
}

