// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cap.proto

package com.google.publicalerts.cap;

public final class Cap {
  private Cap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Group_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Group_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_ValuePair_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_ValuePair_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Point_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Point_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Polygon_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Polygon_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Circle_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Circle_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Area_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Area_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Resource_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Resource_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Info_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Info_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_publicalerts_cap_Alert_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_publicalerts_cap_Alert_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcap.proto\022\020publicalerts.cap\"\026\n\005Group\022\r" +
      "\n\005value\030\001 \003(\t\".\n\tValuePair\022\022\n\nvalue_name" +
      "\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\",\n\005Point\022\020\n\010latitu" +
      "de\030\001 \002(\001\022\021\n\tlongitude\030\002 \002(\001\"1\n\007Polygon\022&" +
      "\n\005point\030\001 \003(\0132\027.publicalerts.cap.Point\"@" +
      "\n\006Circle\022&\n\005point\030\001 \002(\0132\027.publicalerts.c" +
      "ap.Point\022\016\n\006radius\030\002 \002(\001\"\300\001\n\004Area\022\021\n\tare" +
      "a_desc\030\001 \002(\t\022*\n\007polygon\030\002 \003(\0132\031.publical" +
      "erts.cap.Polygon\022(\n\006circle\030\003 \003(\0132\030.publi" +
      "calerts.cap.Circle\022,\n\007geocode\030\004 \003(\0132\033.pu",
      "blicalerts.cap.ValuePair\022\020\n\010altitude\030\005 \001" +
      "(\001\022\017\n\007ceiling\030\006 \001(\001\"r\n\010Resource\022\025\n\rresou" +
      "rce_desc\030\001 \002(\t\022\021\n\tmime_type\030\002 \001(\t\022\014\n\004siz" +
      "e\030\003 \001(\003\022\013\n\003uri\030\004 \001(\t\022\021\n\tderef_uri\030\005 \001(\t\022" +
      "\016\n\006digest\030\006 \001(\t\"\310\t\n\004Info\022\027\n\010language\030\001 \001" +
      "(\t:\005en-US\0221\n\010category\030\002 \003(\0162\037.publicaler" +
      "ts.cap.Info.Category\022\r\n\005event\030\003 \002(\t\022:\n\rr" +
      "esponse_type\030\004 \003(\0162#.publicalerts.cap.In" +
      "fo.ResponseType\022/\n\007urgency\030\005 \002(\0162\036.publi" +
      "calerts.cap.Info.Urgency\0221\n\010severity\030\006 \002",
      "(\0162\037.publicalerts.cap.Info.Severity\0223\n\tc" +
      "ertainty\030\007 \002(\0162 .publicalerts.cap.Info.C" +
      "ertainty\022\020\n\010audience\030\010 \001(\t\022/\n\nevent_code" +
      "\030\t \003(\0132\033.publicalerts.cap.ValuePair\022\021\n\te" +
      "ffective\030\n \001(\t\022\r\n\005onset\030\013 \001(\t\022\017\n\007expires" +
      "\030\014 \001(\t\022\023\n\013sender_name\030\r \001(\t\022\020\n\010headline\030" +
      "\016 \001(\t\022\023\n\013description\030\017 \001(\t\022\023\n\013instructio" +
      "n\030\020 \001(\t\022\013\n\003web\030\021 \001(\t\022\017\n\007contact\030\022 \001(\t\022.\n" +
      "\tparameter\030\023 \003(\0132\033.publicalerts.cap.Valu" +
      "ePair\022,\n\010resource\030\024 \003(\0132\032.publicalerts.c",
      "ap.Resource\022$\n\004area\030\025 \003(\0132\026.publicalerts" +
      ".cap.Area\"\221\001\n\010Category\022\007\n\003GEO\020\000\022\007\n\003MET\020\001" +
      "\022\n\n\006SAFETY\020\002\022\014\n\010SECURITY\020\003\022\n\n\006RESCUE\020\004\022\010" +
      "\n\004FIRE\020\005\022\n\n\006HEALTH\020\006\022\007\n\003ENV\020\007\022\r\n\tTRANSPO" +
      "RT\020\010\022\t\n\005INFRA\020\t\022\t\n\005CBRNE\020\n\022\t\n\005OTHER\020\013\"\200\001" +
      "\n\014ResponseType\022\013\n\007SHELTER\020\000\022\014\n\010EVACUATE\020" +
      "\001\022\013\n\007PREPARE\020\002\022\013\n\007EXECUTE\020\003\022\t\n\005AVOID\020\004\022\013" +
      "\n\007MONITOR\020\005\022\n\n\006ASSESS\020\006\022\r\n\tALL_CLEAR\020\007\022\010" +
      "\n\004NONE\020\010\"Q\n\007Urgency\022\r\n\tIMMEDIATE\020\000\022\014\n\010EX" +
      "PECTED\020\001\022\n\n\006FUTURE\020\002\022\010\n\004PAST\020\003\022\023\n\017UNKNOW",
      "N_URGENCY\020\004\"R\n\010Severity\022\013\n\007EXTREME\020\000\022\n\n\006" +
      "SEVERE\020\001\022\014\n\010MODERATE\020\002\022\t\n\005MINOR\020\003\022\024\n\020UNK" +
      "NOWN_SEVERITY\020\004\"i\n\tCertainty\022\014\n\010OBSERVED" +
      "\020\000\022\017\n\013VERY_LIKELY\020\001\022\n\n\006LIKELY\020\002\022\014\n\010POSSI" +
      "BLE\020\003\022\014\n\010UNLIKELY\020\004\022\025\n\021UNKNOWN_CERTAINTY" +
      "\020\005\"\224\005\n\005Alert\022\r\n\005xmlns\030\001 \002(\t\022\022\n\nidentifie" +
      "r\030\002 \002(\t\022\016\n\006sender\030\003 \002(\t\022\024\n\010password\030\004 \001(" +
      "\tB\002\030\001\022\014\n\004sent\030\005 \002(\t\022.\n\006status\030\006 \002(\0162\036.pu" +
      "blicalerts.cap.Alert.Status\0221\n\010msg_type\030" +
      "\007 \002(\0162\037.publicalerts.cap.Alert.MsgType\022\016",
      "\n\006source\030\010 \001(\t\022,\n\005scope\030\t \001(\0162\035.publical" +
      "erts.cap.Alert.Scope\022\023\n\013restriction\030\n \001(" +
      "\t\022*\n\taddresses\030\013 \001(\0132\027.publicalerts.cap." +
      "Group\022\014\n\004code\030\014 \003(\t\022\014\n\004note\030\r \001(\t\022+\n\nref" +
      "erences\030\016 \001(\0132\027.publicalerts.cap.Group\022*" +
      "\n\tincidents\030\017 \001(\0132\027.publicalerts.cap.Gro" +
      "up\022$\n\004info\030\020 \003(\0132\026.publicalerts.cap.Info" +
      "\"C\n\006Status\022\n\n\006ACTUAL\020\000\022\014\n\010EXERCISE\020\001\022\n\n\006" +
      "SYSTEM\020\002\022\010\n\004TEST\020\003\022\t\n\005DRAFT\020\004\"@\n\007MsgType" +
      "\022\t\n\005ALERT\020\000\022\n\n\006UPDATE\020\001\022\n\n\006CANCEL\020\002\022\007\n\003A",
      "CK\020\003\022\t\n\005ERROR\020\004\"0\n\005Scope\022\n\n\006PUBLIC\020\000\022\016\n\n" +
      "RESTRICTED\020\001\022\013\n\007PRIVATE\020\002B\'\n\033com.google." +
      "publicalerts.capB\003CapP\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_publicalerts_cap_Group_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_publicalerts_cap_Group_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Group_descriptor,
              new java.lang.String[] { "Value", },
              com.google.publicalerts.cap.Group.class,
              com.google.publicalerts.cap.Group.Builder.class);
          internal_static_publicalerts_cap_ValuePair_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_publicalerts_cap_ValuePair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_ValuePair_descriptor,
              new java.lang.String[] { "ValueName", "Value", },
              com.google.publicalerts.cap.ValuePair.class,
              com.google.publicalerts.cap.ValuePair.Builder.class);
          internal_static_publicalerts_cap_Point_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_publicalerts_cap_Point_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Point_descriptor,
              new java.lang.String[] { "Latitude", "Longitude", },
              com.google.publicalerts.cap.Point.class,
              com.google.publicalerts.cap.Point.Builder.class);
          internal_static_publicalerts_cap_Polygon_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_publicalerts_cap_Polygon_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Polygon_descriptor,
              new java.lang.String[] { "Point", },
              com.google.publicalerts.cap.Polygon.class,
              com.google.publicalerts.cap.Polygon.Builder.class);
          internal_static_publicalerts_cap_Circle_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_publicalerts_cap_Circle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Circle_descriptor,
              new java.lang.String[] { "Point", "Radius", },
              com.google.publicalerts.cap.Circle.class,
              com.google.publicalerts.cap.Circle.Builder.class);
          internal_static_publicalerts_cap_Area_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_publicalerts_cap_Area_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Area_descriptor,
              new java.lang.String[] { "AreaDesc", "Polygon", "Circle", "Geocode", "Altitude", "Ceiling", },
              com.google.publicalerts.cap.Area.class,
              com.google.publicalerts.cap.Area.Builder.class);
          internal_static_publicalerts_cap_Resource_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_publicalerts_cap_Resource_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Resource_descriptor,
              new java.lang.String[] { "ResourceDesc", "MimeType", "Size", "Uri", "DerefUri", "Digest", },
              com.google.publicalerts.cap.Resource.class,
              com.google.publicalerts.cap.Resource.Builder.class);
          internal_static_publicalerts_cap_Info_descriptor =
            getDescriptor().getMessageTypes().get(7);
          internal_static_publicalerts_cap_Info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Info_descriptor,
              new java.lang.String[] { "Language", "Category", "Event", "ResponseType", "Urgency", "Severity", "Certainty", "Audience", "EventCode", "Effective", "Onset", "Expires", "SenderName", "Headline", "Description", "Instruction", "Web", "Contact", "Parameter", "Resource", "Area", },
              com.google.publicalerts.cap.Info.class,
              com.google.publicalerts.cap.Info.Builder.class);
          internal_static_publicalerts_cap_Alert_descriptor =
            getDescriptor().getMessageTypes().get(8);
          internal_static_publicalerts_cap_Alert_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_publicalerts_cap_Alert_descriptor,
              new java.lang.String[] { "Xmlns", "Identifier", "Sender", "Password", "Sent", "Status", "MsgType", "Source", "Scope", "Restriction", "Addresses", "Code", "Note", "References", "Incidents", "Info", },
              com.google.publicalerts.cap.Alert.class,
              com.google.publicalerts.cap.Alert.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
