// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/cap.proto

package com.google.publicalerts.cap;

public final class Cap {
  private Cap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Group_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Group_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_ValuePair_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_ValuePair_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Point_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Point_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Polygon_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Polygon_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Circle_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Circle_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Area_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Area_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Resource_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Resource_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Info_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Info_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_alerts_cap_Alert_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alerts_cap_Alert_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/cap.proto\022\nalerts.cap\"\026\n\005Group\022\r" +
      "\n\005value\030\001 \003(\t\".\n\tValuePair\022\022\n\nvalue_name" +
      "\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\",\n\005Point\022\020\n\010latitu" +
      "de\030\001 \002(\001\022\021\n\tlongitude\030\002 \002(\001\"+\n\007Polygon\022 " +
      "\n\005point\030\001 \003(\0132\021.alerts.cap.Point\":\n\006Circ" +
      "le\022 \n\005point\030\001 \002(\0132\021.alerts.cap.Point\022\016\n\006" +
      "radius\030\002 \002(\001\"\256\001\n\004Area\022\021\n\tarea_desc\030\001 \002(\t" +
      "\022$\n\007polygon\030\002 \003(\0132\023.alerts.cap.Polygon\022\"" +
      "\n\006circle\030\003 \003(\0132\022.alerts.cap.Circle\022&\n\007ge" +
      "ocode\030\004 \003(\0132\025.alerts.cap.ValuePair\022\020\n\010al",
      "titude\030\005 \001(\001\022\017\n\007ceiling\030\006 \001(\001\"r\n\010Resourc" +
      "e\022\025\n\rresource_desc\030\001 \002(\t\022\021\n\tmime_type\030\002 " +
      "\001(\t\022\014\n\004size\030\003 \001(\003\022\013\n\003uri\030\004 \001(\t\022\021\n\tderef_" +
      "uri\030\005 \001(\t\022\016\n\006digest\030\006 \001(\t\"\217\t\n\004Info\022\027\n\010la" +
      "nguage\030\001 \001(\t:\005en-US\022+\n\010category\030\002 \003(\0162\031." +
      "alerts.cap.Info.Category\022\r\n\005event\030\003 \002(\t\022" +
      "4\n\rresponse_type\030\004 \003(\0162\035.alerts.cap.Info" +
      ".ResponseType\022)\n\007urgency\030\005 \002(\0162\030.alerts." +
      "cap.Info.Urgency\022+\n\010severity\030\006 \002(\0162\031.ale" +
      "rts.cap.Info.Severity\022-\n\tcertainty\030\007 \002(\016",
      "2\032.alerts.cap.Info.Certainty\022\020\n\010audience" +
      "\030\010 \001(\t\022)\n\nevent_code\030\t \003(\0132\025.alerts.cap." +
      "ValuePair\022\021\n\teffective\030\n \001(\t\022\r\n\005onset\030\013 " +
      "\001(\t\022\017\n\007expires\030\014 \001(\t\022\023\n\013sender_name\030\r \001(" +
      "\t\022\020\n\010headline\030\016 \001(\t\022\023\n\013description\030\017 \001(\t" +
      "\022\023\n\013instruction\030\020 \001(\t\022\013\n\003web\030\021 \001(\t\022\017\n\007co" +
      "ntact\030\022 \001(\t\022(\n\tparameter\030\023 \003(\0132\025.alerts." +
      "cap.ValuePair\022&\n\010resource\030\024 \003(\0132\024.alerts" +
      ".cap.Resource\022\036\n\004area\030\025 \003(\0132\020.alerts.cap" +
      ".Area\"\221\001\n\010Category\022\007\n\003Geo\020\000\022\007\n\003Met\020\001\022\n\n\006",
      "Safety\020\002\022\014\n\010Security\020\003\022\n\n\006Rescue\020\004\022\010\n\004Fi" +
      "re\020\005\022\n\n\006Health\020\006\022\007\n\003Env\020\007\022\r\n\tTransport\020\010" +
      "\022\t\n\005Infra\020\t\022\t\n\005CBRNE\020\n\022\t\n\005Other\020\013\"\177\n\014Res" +
      "ponseType\022\013\n\007Shelter\020\000\022\014\n\010Evacuate\020\001\022\013\n\007" +
      "Prepare\020\002\022\013\n\007Execute\020\003\022\t\n\005Avoid\020\004\022\013\n\007Mon" +
      "itor\020\005\022\n\n\006Assess\020\006\022\014\n\010AllClear\020\007\022\010\n\004None" +
      "\020\010\"Q\n\007Urgency\022\r\n\tImmediate\020\000\022\014\n\010Expected" +
      "\020\001\022\n\n\006Future\020\002\022\010\n\004Past\020\003\022\023\n\017Unknown_Urge" +
      "ncy\020\004\"R\n\010Severity\022\013\n\007Extreme\020\000\022\n\n\006Severe" +
      "\020\001\022\014\n\010Moderate\020\002\022\t\n\005Minor\020\003\022\024\n\020Unknown_S",
      "everity\020\004\"h\n\tCertainty\022\014\n\010Observed\020\000\022\016\n\n" +
      "VeryLikely\020\001\022\n\n\006Likely\020\002\022\014\n\010Possible\020\003\022\014" +
      "\n\010Unlikely\020\004\022\025\n\021Unknown_Certainty\020\005\"\352\004\n\005" +
      "Alert\022\r\n\005xmlns\030\001 \002(\t\022\022\n\nidentifier\030\002 \002(\t" +
      "\022\016\n\006sender\030\003 \002(\t\022\024\n\010password\030\004 \001(\tB\002\030\001\022\014" +
      "\n\004sent\030\005 \002(\t\022(\n\006status\030\006 \002(\0162\030.alerts.ca" +
      "p.Alert.Status\022+\n\010msg_type\030\007 \002(\0162\031.alert" +
      "s.cap.Alert.MsgType\022\016\n\006source\030\010 \001(\t\022&\n\005s" +
      "cope\030\t \001(\0162\027.alerts.cap.Alert.Scope\022\023\n\013r" +
      "estriction\030\n \001(\t\022$\n\taddresses\030\013 \001(\0132\021.al",
      "erts.cap.Group\022\014\n\004code\030\014 \003(\t\022\014\n\004note\030\r \001" +
      "(\t\022%\n\nreferences\030\016 \001(\0132\021.alerts.cap.Grou" +
      "p\022$\n\tincidents\030\017 \001(\0132\021.alerts.cap.Group\022" +
      "\036\n\004info\030\020 \003(\0132\020.alerts.cap.Info\"C\n\006Statu" +
      "s\022\n\n\006Actual\020\000\022\014\n\010Exercise\020\001\022\n\n\006System\020\002\022" +
      "\010\n\004Test\020\003\022\t\n\005Draft\020\004\"@\n\007MsgType\022\t\n\005Alert" +
      "\020\000\022\n\n\006Update\020\001\022\n\n\006Cancel\020\002\022\007\n\003Ack\020\003\022\t\n\005E" +
      "rror\020\004\"0\n\005Scope\022\n\n\006Public\020\000\022\016\n\nRestricte" +
      "d\020\001\022\013\n\007Private\020\002B\'\n\033com.google.publicale" +
      "rts.capB\003CapP\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_alerts_cap_Group_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_alerts_cap_Group_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Group_descriptor,
              new java.lang.String[] { "Value", },
              com.google.publicalerts.cap.Group.class,
              com.google.publicalerts.cap.Group.Builder.class);
          internal_static_alerts_cap_ValuePair_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_alerts_cap_ValuePair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_ValuePair_descriptor,
              new java.lang.String[] { "ValueName", "Value", },
              com.google.publicalerts.cap.ValuePair.class,
              com.google.publicalerts.cap.ValuePair.Builder.class);
          internal_static_alerts_cap_Point_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_alerts_cap_Point_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Point_descriptor,
              new java.lang.String[] { "Latitude", "Longitude", },
              com.google.publicalerts.cap.Point.class,
              com.google.publicalerts.cap.Point.Builder.class);
          internal_static_alerts_cap_Polygon_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_alerts_cap_Polygon_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Polygon_descriptor,
              new java.lang.String[] { "Point", },
              com.google.publicalerts.cap.Polygon.class,
              com.google.publicalerts.cap.Polygon.Builder.class);
          internal_static_alerts_cap_Circle_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_alerts_cap_Circle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Circle_descriptor,
              new java.lang.String[] { "Point", "Radius", },
              com.google.publicalerts.cap.Circle.class,
              com.google.publicalerts.cap.Circle.Builder.class);
          internal_static_alerts_cap_Area_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_alerts_cap_Area_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Area_descriptor,
              new java.lang.String[] { "AreaDesc", "Polygon", "Circle", "Geocode", "Altitude", "Ceiling", },
              com.google.publicalerts.cap.Area.class,
              com.google.publicalerts.cap.Area.Builder.class);
          internal_static_alerts_cap_Resource_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_alerts_cap_Resource_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Resource_descriptor,
              new java.lang.String[] { "ResourceDesc", "MimeType", "Size", "Uri", "DerefUri", "Digest", },
              com.google.publicalerts.cap.Resource.class,
              com.google.publicalerts.cap.Resource.Builder.class);
          internal_static_alerts_cap_Info_descriptor =
            getDescriptor().getMessageTypes().get(7);
          internal_static_alerts_cap_Info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Info_descriptor,
              new java.lang.String[] { "Language", "Category", "Event", "ResponseType", "Urgency", "Severity", "Certainty", "Audience", "EventCode", "Effective", "Onset", "Expires", "SenderName", "Headline", "Description", "Instruction", "Web", "Contact", "Parameter", "Resource", "Area", },
              com.google.publicalerts.cap.Info.class,
              com.google.publicalerts.cap.Info.Builder.class);
          internal_static_alerts_cap_Alert_descriptor =
            getDescriptor().getMessageTypes().get(8);
          internal_static_alerts_cap_Alert_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alerts_cap_Alert_descriptor,
              new java.lang.String[] { "Xmlns", "Identifier", "Sender", "Password", "Sent", "Status", "MsgType", "Source", "Scope", "Restriction", "Addresses", "Code", "Note", "References", "Incidents", "Info", },
              com.google.publicalerts.cap.Alert.class,
              com.google.publicalerts.cap.Alert.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
