// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.publicalerts.cap;

public interface CircleOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required .publicalerts.cap.Point point = 1;
  boolean hasPoint();
  com.google.publicalerts.cap.Point getPoint();
  com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder();
  
  // required double radius = 2;
  boolean hasRadius();
  double getRadius();
}
