// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.publicalerts.cap;

public interface PointOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required double latitude = 1;
  boolean hasLatitude();
  double getLatitude();
  
  // required double longitude = 2;
  boolean hasLongitude();
  double getLongitude();
}
