// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.publicalerts.cap;

public interface PolygonOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // repeated .publicalerts.cap.Point point = 1;
  java.util.List<com.google.publicalerts.cap.Point> 
      getPointList();
  com.google.publicalerts.cap.Point getPoint(int index);
  int getPointCount();
  java.util.List<? extends com.google.publicalerts.cap.PointOrBuilder> 
      getPointOrBuilderList();
  com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder(
      int index);
}
