// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.publicalerts.cap;

public interface ResourceOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required string resource_desc = 1;
  boolean hasResourceDesc();
  String getResourceDesc();
  
  // optional string mime_type = 2;
  boolean hasMimeType();
  String getMimeType();
  
  // optional int64 size = 3;
  boolean hasSize();
  long getSize();
  
  // optional string uri = 4;
  boolean hasUri();
  String getUri();
  
  // optional string deref_uri = 5;
  boolean hasDerefUri();
  String getDerefUri();
  
  // optional string digest = 6;
  boolean hasDigest();
  String getDigest();
}
