// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.publicalerts.cap;

public interface ValuePairOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required string value_name = 1;
  boolean hasValueName();
  String getValueName();
  
  // required string value = 2;
  boolean hasValue();
  String getValue();
}
