// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.publicalerts.cap;

public interface GroupOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // repeated string value = 1;
  java.util.List<String> getValueList();
  int getValueCount();
  String getValue(int index);
}
